[[constraint]]
  name = "gopkg.in/fsnotify.v1"
  version = "1.4.7"

[prune]
  go-tests = true
  unused-packages = true

# Fixes https://github.com/golang/dep/issues/1760

[[override]]
  name = "gopkg.in/fsnotify.v1"
  version = "1.2.9"
  source = "https://github.com/fsnotify/fsnotify.git"
